<?php

namespace Shop_products\Models;

/**
 * ProductRate
 * 
 * @package Shop_products\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2019-01-11, 16:39:07
 */
class ProductRates extends BaseModel
{

    /**
     * @var string
     * @Primary
     * @Column(column='rate_id', type='string', length=36)
     */
    public $rateId;

    /**
     * @var string
     * @Column(column='rate_user_id', type='string', length=36)
     */
    public $rateUserId;

    /**
     * @var string
     * @Column(column='product_id', type='string', length=36)
     */
    public $productId;

    /**
     * @var string
     * @Column(column='rate_text', type='text', nullable=true)
     */
    public $rateText;

    /**
     * @var string
     * @Column(column='rate_stars', type='integer', length=11)
     */
    public $rateStars;

    /**
     * @var string
     * @Column(column='created_at', type='datetime')
     */
    public $createdAt;

    /**
     * @var string
     * @Column(column='updated_at', type='datetime', nullable=true)
     */
    public $updatedAt;

    /**
     * @var string
     * @Column(column='deleted_at', type='datetime', nullable=true)
     */
    public $deletedAt;

    /** @var array */
    private $images;

    /**
     * @var bool
     * @Column(column='is_deleted', type='boolean', default=0)
     */
    public $isDeleted;

    public function onConstruct()
    {
        self::$instance = $this;
    }

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema('shop_products');
        $this->setSource('product_rates');
        $this->belongsTo(
            'rateProductId',
            Product::class,
            'productId',
            [
                'reusable' => true
            ]
        );

        $this->hasMany('rate_id', RateImages::class, 'rate_id', ['alias' => 'rateImages']);
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'product_rates';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return ProductRates[]|ProductRates|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return ProductRates|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    public function afterFetch()
    {
        $images = [];
        if (!empty($this->rateImages)) {
            $this->rateImages->filter(function ($image) use(&$images) {
                $images[] = $image->toApiArray();
            });
        }

        $this->images = $images;
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'rate_id' => 'rateId',
            'rate_user_id' => 'rateUserId',
            'product_id' => 'productId',
            'rate_text' => 'rateText',
            'rate_stars' => 'rateStars',
            'created_at' => 'createdAt',
            'updated_at' => 'updatedAt',
            'deleted_at' => 'deletedAt',
            'is_deleted' => 'isDeleted'
        ];
    }

    public function toApiArray()
    {
        return [
            'rateId' => $this->rateId,
            'rateUserId' => $this->rateUserId,
            'productId' => $this->productId,
            'rateText' => $this->rateText,
            'rateStars' => $this->rateStars,
            'rateImages' => $this->images
        ];
    }
}
