<?php

namespace Shop_products\Models;

/**
 * ProductQuestions
 * 
 * @package Shop_products\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2019-01-13, 09:24:22
 */
class ProductQuestions extends BaseModel
{

    /**
     *
     * @var string
     */
    public $questionId;

    /**
     *
     * @var string
     */
    public $questionProductId;

    /**
     *
     * @var string
     */
    public $questionUserId;

    /**
     *
     * @var string
     */
    public $questionText;

    /**
     *
     * @var string
     */
    public $createdAt;

    /**
     *
     * @var string
     */
    public $deletedAt;

    /**
     *
     * @var integer
     */
    public $isDeleted;

    public function onConstruct()
    {
        self::$instance = $this;
    }

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("shop_products");
        $this->setSource("product_questions");
        $this->useDynamicUpdate(true);
        $this->belongsTo('questionProductId', 'Shop_products\Models\Product', 'productId', ['alias' => 'Product']);
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'product_questions';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return ProductQuestions[]|ProductQuestions|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return ProductQuestions|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'question_id' => 'questionId',
            'question_product_id' => 'questionProductId',
            'question_user_id' => 'questionUserId',
            'question_text' => 'questionText',
            'created_at' => 'createdAt',
            'deleted_at' => 'deletedAt',
            'is_deleted' => 'isDeleted'
        ];
    }

}
