<?php

namespace Shop_products\Models;

/**
 * ProductRate
 * 
 * @package Shop_products\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2019-01-11, 16:39:07
 */
class ProductRates extends BaseModel
{

    /**
     *
     * @var string
     */
    public $rateId;

    /**
     *
     * @var string
     */
    public $rateUserId;

    /**
     *
     * @var string
     */
    public $rateProductId;

    /**
     *
     * @var string
     */
    public $rateText;

    /**
     *
     * @var string
     */
    public $rateStars;

    /**
     *
     * @var string
     */
    public $rateImages;

    /**
     *
     * @var string
     */
    public $createdAt;

    /**
     *
     * @var string
     */
    public $updatedAt;

    /**
     *
     * @var string
     */
    public $deletedAt;

    /**
     *
     * @var integer
     */
    public $isDeleted;

    public function onConstruct()
    {
        self::$instance = $this;
    }

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("shop_products");
        $this->setSource("product_rates");
        $this->belongsTo('rateProductId', 'Shop_products\Models\Product', 'productId', ['alias' => 'Product']);
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'product_rates';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return ProductRates[]|ProductRates|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return ProductRates|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'rate_id' => 'rateId',
            'rate_user_id' => 'rateUserId',
            'rate_product_id' => 'rateProductId',
            'rate_text' => 'rateText',
            'rate_stars' => 'rateStars',
            'rate_images' => 'rateImages',
            'created_at' => 'createdAt',
            'updated_at' => 'updatedAt',
            'deleted_at' => 'deletedAt',
            'is_deleted' => 'isDeleted'
        ];
    }

}
