version: '3.3'
services:
  products-sync:
    build: .
    image: 'shop/products'
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: >
      bash -c "chmod +x utilities/start_service.sh
      && utilities/start_service.sh
      && ./run consumer syncConsumer"

  products-async:
    build: .
    image: 'shop/products'
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: >
      bash -c "chmod +x utilities/start_service.sh
      && utilities/start_service.sh
      && ./run consumer asyncConsumer"

  products-api:
    build: .
    image: 'shop/products'
    working_dir: /var/www/html
    ports:
      - "1001:8000"
    volumes:
      - .:/var/www/html
    command: >
      bash -c "chmod +x utilities/start_service.sh
      && utilities/start_service.sh
      && rm -f /var/www/html/public/webtools*
      && phalcon webtools enable
      && phalcon serve"
  products-unit-test:
    build: .
    image: 'shop/products'
    volumes:
      - .:/var/www/html
    command: >
      bash -c "chmod +x utilities/start_service.sh
      && utilities/start_service.sh
      && app/common/library/vendor/bin/phpunit -c tests/phpunit.xml"

networks:
  default:
    external:
      name: marketplace-network

