version: '3.3'
services:
  shop-products-sync:
    build: .
    image: 'shop/products'
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: >
      bash -c "chmod +x utilities/start_service.sh
      && utilities/start_service.sh
      && ./run consumer syncConsumer"

  shop-products-async:
    build: .
    image: 'shop/products'
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: >
      bash -c "chmod +x utilities/start_service.sh
      && utilities/start_service.sh
      && ./run consumer asyncConsumer"

  shop-products-api:
    build: .
    image: 'shop/products'
    working_dir: /var/www/html
    ports:
      - "1002:80"
    volumes:
      - .:/var/www/html
    command: >
      bash -c "chmod +x utilities/start_service.sh
      && utilities/start_service.sh
      && php -S 0.0.0.0:80 -t /var/www/html/public"

networks:
  default:
    external:
      name: marketplace-network

