version: '3.3'
services:
  products-api:
    image: marketplace_shop_products
    build:
      context: .
    command: phalcon serve
    env_file:
      - .env
    environment:
      - PHP_IDE_CONFIG=serverName=docker
    volumes:
      - .:/src
      - /src/app/vendor
    ports:
      - "1001:8000"

  products-sync:
    image: marketplace_shop_products
    command: bash -c "./run consumer syncConsumer | phalcon serve"
    env_file:
      - .env
    environment:
      - PHP_IDE_CONFIG=serverName=docker
    volumes:
      - .:/src
      - /src/app/vendor
    depends_on:
      - products-api

  products-async:
    image: marketplace_shop_products
    command: bash -c "./run consumer asyncConsumer | phalcon serve"
    env_file:
      - .env
    environment:
      - PHP_IDE_CONFIG=serverName=docker
    volumes:
      - .:/src
      - /src/app/vendor
    depends_on:
      - products-api

  products-unit-test:
    image: marketplace_shop_products
    command: app/vendor/bin/phpunit -c tests/phpunit.xml
    volumes:
      - .:/src
      - /src/app/vendor
    env_file:
      - .env
    environment:
      - UNIT_TEST=1

networks:
  default:
    external:
      name: marketplace-network

