version: '3.3'
services:
  products-api:
    build:
      context: .
    ports:
      - "1001:8000"
    command: phalcon serve
    environment:
      - PHP_IDE_CONFIG=serverName=docker
    volumes:
      - .:/src
      - /src/app/vendor

  products-sync:
    build:
      context: .
    command: bash -c "./run consumer syncConsumer | phalcon serve"
    environment:
      - PHP_IDE_CONFIG=serverName=docker
    volumes:
      - .:/src
      - /src/app/vendor
    depends_on:
      - products-api

  products-async:
    build:
      context: .
    command: bash -c "./run consumer asyncConsumer | phalcon serve"
    environment:
      - PHP_IDE_CONFIG=serverName=docker
    volumes:
      - .:/src
      - /src/app/vendor
    depends_on:
      - products-api

  products-unit-test:
    build:
      context: .
    command: app/vendor/bin/phpunit -c tests/phpunit.xml
    volumes:
      - .:/src
      - /src/app/vendor

networks:
  default:
    external:
      name: marketplace-network

