version: '3.3'
services:
  products-sync:
    image: 'registry.gitlab.com/shop_ecommerce/shop_products'
    command: ./run consumer syncConsumer
    volumes:
      - .:/src
      - /src/app/vendor

  products-async:
    image: 'registry.gitlab.com/shop_ecommerce/shop_products'
    command: ./run consumer asyncConsumer
    volumes:
      - .:/src
      - /src/app/vendor

  products-api:
    image: 'registry.gitlab.com/shop_ecommerce/shop_products'
    ports:
      - "1001:8000"
    command: >
      bash -c "rm -f /src/public/webtools*
      && phalcon webtools enable
      && phalcon serve"
    volumes:
      - .:/src
      - /src/app/vendor

  products-unit-test:
    image: 'registry.gitlab.com/shop_ecommerce/shop_products'
    command: app/vendor/bin/phpunit -c tests/phpunit.xml
    volumes:
      - .:/src
      - /src/app/vendor

networks:
  default:
    external:
      name: marketplace-network

