version: '1.0'
api:
  version: '1.0'

database:
  adapter: Mysql
  host: 0.0.0.0
  port: 3306
  username: phalcon
  password: secret
  dbname: shop_products
  charset: utf8

mongodb:
  host: 0.0.0.0
  username:
  password:
  port: 27017
  dbname: shop_products

cache:
  products_cache:
    host: 0.0.0.0
    port: 6379
    persistent: true
    database: 0
    ttl: -1
    auth:
  images_cache:
    host: 0.0.0.0
    port: 6379
    persistent: true
    database: 1
    ttl: -1
    auth:
  questions_cache:
    host: 0.0.0.0
    port: 6379
    persistent: true
    database: 2
    ttl: -1
    auth:
  rates_cache:
    host: 0.0.0.0
    port: 6379
    persistent: true
    database: 3
    ttl: -1
    auth:

rabbitmq:
  host: 0.0.0.0
  port: 5672
  username: guest
  password: guest
  sync_queue:
    queue_name: products_sync
    message_ttl: 10000
  async_queue:
    queue_name: products_async
    message_ttl: 10000
  rpc:
    queue_name: rpc_queue

application:
  modelsDir: !appDir /common/models/
  collectionsDir: !appDir /common/collections/
  migrationsDir: !appDir /migrations/
  logsDir: !appDir /logs/
  uploadDir: !baseDir /public/uploads/
  imgur:
    apiKey: fde8e22da065b65
    apiSecret: 09b2fcc7e71311b414ac5b16e37191e96f303735
    accessToken: 6b02a3b092cadf34e1b9a84c01ab896ff3a7e7d1
  token:
    saltKey: abc@123456789012
    allowedAlg: HS512
printNewLine: true
