name: docker

on:
    push:
        # publish image as master=dev or on new tag
        # except on document and ci changes
        branches:
            - main
        tags:
            - '*'
        paths-ignore:
            - '**.md'
            - '.github/workflows/*yml'

    # always run tests on merge
    # except on document and ci changes
    pull_request:
        paths-ignore:
            - '**.md'
            - '.github/workflows/*yml'

jobs:
    unit_test:
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        services:
            mysql:
                image: mysql:8
                ports:
                    - 3306
                env:
                    MYSQL_USER: phalcon
                    MYSQL_PASSWORD: secret
                    MYSQL_DATABASE: shop_products_test
                    MYSQL_ROOT_PASSWORD: root
                options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
        steps:
            - name: Create docker network
              run: docker network create marketplace-network
            - name: Check out Site Repository 📄
              uses: actions/checkout@v2
            - name: Create .env file
              run: cp .env.example .env
            - name: Replace hosts with MySQL IP address
              run: sed -i 's/MYSQL_HOST.*/MYSQL_HOST=127.0.0.1/g' .env
            - name: Import environment variables from a file
              id: import-env
              shell: bash
              run: |
                while read line; do
                  echo "$line" >> $GITHUB_ENV
                  done < .env
            - name: Verify MySQL connection
              env:
                PORT: ${{ job.services.mysql.ports[3306] }}
              run: |
                while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
                  sleep 1
                done
            - name: Running unit test
              run: docker-compose up products-unit-test