name: docker

on:
    push:
        # publish image as master=dev or on new tag
        # except on document and ci changes
        branches:
            - master
        tags:
            - '*'
        paths-ignore:
            - '**.md'
            - '.github/workflows/*yml'

    # always run tests on merge
    # except on document and ci changes
    pull_request:
        paths-ignore:
            - '**.md'
            - '.github/workflows/*yml'

env:
    # TODO: remember to update version on new tag
    LATEST_TAG: 1.0.0
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: shop_products
    MYSQL_USER: phalcon
    MYSQL_PASSWORD: secret

jobs:
    unit_test:
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        steps:
            - name: Check out Site Repository 📄
              uses: actions/checkout@v2
            - name: Create MySQL container
              run: |
                docker run --name marketplace-mysql \
                  --network marketplace-network \
                  -p 3306:3306 \
                  -e MYSQL_ROOT_PASSWORD={$MYSQL_ROOT_PASSWORD} \
                  -e MYSQL_DATABASE={$MYSQL_DATABASE}
                  -d mysql:8 \
                  mysql -uroot -proot \
                  -e "CREATE USER '{$MYSQL_USER}' IDENTIFIED WITH mysql_native_password BY '{$MYSQL_PASSWORD}'; \
                    GRANT ALL PRIVILEGES ON shop_products.* TO phalcon;"
            - name: Create docker network
              run: docker network create marketplace-network
            - name: Running unit test
              run: docker-compose up products-unit-test