name: docker

on:
    push:
        # publish image as master=dev or on new tag
        # except on document and ci changes
        branches:
            - master
        tags:
            - '*'
        paths-ignore:
            - '**.md'
            - '.github/workflows/*yml'

    # always run tests on merge
    # except on document and ci changes
    pull_request:
        paths-ignore:
            - '**.md'
            - '.github/workflows/*yml'

env:
    # TODO: remember to update version on new tag
    LATEST_TAG: 1.0.0

jobs:
    unit_test:
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        steps:
            - name: Display list of folders
              run: ls -la
            - name: Create docker network
              run: docker network create marketplace-network
            - name: Running unit test
              run: docker-compose -f ../../docker-compose.yml up products-unit-test