name: docker

on:
    push:
        # publish image as master=dev or on new tag
        # except on document and ci changes
        branches:
            - main
        tags:
            - '*'
        paths-ignore:
            - '**.md'
            - '.github/workflows/*yml'

    # always run tests on merge
    # except on document and ci changes
    pull_request:
        paths-ignore:
            - '**.md'
            - '.github/workflows/*yml'

jobs:
    unit_test:
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        steps:
            - name: Create docker network
              run: docker network create marketplace-network
            - name: Check out Site Repository 📄
              uses: actions/checkout@v2
            - name: Create .env file
              run: cp .env.example .env
            - name: Replace hosts with MySQL IP address
              run: sed -i 's/MYSQL_HOST.*/MYSQL_HOST=0.0.0.0/g' .env
            - name: Import environment variables from a file
              id: import-env
              shell: bash
              run: |
                while read line; do
                  echo "$line" >> $GITHUB_ENV
                  done < .env
            - name: Create MySQL server
              uses: mirromutth/mysql-action@v1.1
              with:
                  mysql version: '8.0'
                  mysql database: 'shop_products_test'
                  mysql user: 'phalcon'
                  mysql password: 'secret'

            - name: Build docker image
              run: docker build -t marketplace_shop_products .
            - name: Running unit test
              run: docker-compose up products-unit-test